# SPDX-FileCopyrightText: 2016-2021 by pi-lar GmbH
# SPDX-License-Identifier: OSL-3.0

default:
  image: $CI_REGISTRY_IMAGE/dev-enviroment

cache:
  key: "${CI_COMMIT_SHA}"
  paths:
    - .venv

stages:
  - distribute


gitlab-release:
  stage: distribute
  script:
    - ./do release
    # auto saltstack deploy
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED && $CI_COMMIT_TAG == null'
      when: manual

pages:
  stage: distribute
  script:
    - wget "https://gitlab.com/$CI_PROJECT_PATH/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=build:documentation" -O "/tmp/$CI_COMMIT_SHA.zip"
    - unzip "/tmp/$CI_COMMIT_SHA.zip"
    - rm "/tmp/$CI_COMMIT_SHA.zip"
    - mkdir -p public
    - mv build/doc/html/* public
  artifacts:
    paths:
    - public/
  rules:
    - if: '$CI_COMMIT_TAG != null && $CI_COMMIT_REF_PROTECTED'
    - if: '$CI_COMMIT_REF_PROTECTED'
      when: manual
