# SPDX-FileCopyrightText: 2016-2022 by pi-lar GmbH
# SPDX-License-Identifier: OSL-3.0

# generated by datamodel-codegen:
#   filename:  node-identity.schema.json
#   timestamp: 2024-08-29T09:57:24+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from .additional_information import AdditionalInformation


class NodeIdentity(BaseModel):

    Domain: str = Field(..., description="Domain of the node.")
    NodeID: str = Field(..., description="ID of the node.")
    IP: str = Field(..., description="IP of the node.")
    additionalInformation: Optional[AdditionalInformation] = Field(
        None, description="Additional information about the node."
    )
