# SPDX-FileCopyrightText: 2016-2022 by pi-lar GmbH
# SPDX-License-Identifier: OSL-3.0

# generated by datamodel-codegen:
#   filename:  flavor.schema.json
#   timestamp: 2024-08-29T09:54:13+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Characteristics(BaseModel):
    Name: Optional[str] = Field(None, description="Name of the flavor.")
    Description: Optional[str] = Field(None, description="Description of the flavor.")
    Tags: Optional[List[str]] = Field(
        None, description="Tags associated with the flavor."
    )
    Plan: Optional[str] = Field(None, description="Plan of the flavor.")
    Latency: Optional[int] = Field(None, description="The latency of the Flavor.")
    SecurityStandards: Optional[List[str]] = Field(
        None, description="Security standards supported by the Flavor (e.g., GDPR)."
    )


class SensorSchema(BaseModel):
    characteristics: Optional[Characteristics] = None
