/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "../include/np_types.h"
#include "../include/neuropil.h"
#include "../include/np_tree.h"

SWIGINTERN struct np_tree_s *new_np_tree_s(void){
	return make_nptree();
    }
SWIGINTERN void delete_np_tree_s(struct np_tree_s *self){
        np_free_tree (self);
    }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_neuropilJNI_new_1np_1tree_1s(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct np_tree_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct np_tree_s *)new_np_tree_s();
  *(struct np_tree_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_delete_1np_1tree_1s(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct np_tree_s **)&jarg1; 
  delete_np_tree_s(arg1);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1s_1np_1clear_1tree(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  $self *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return ;
  }
  arg2 = *argp2; 
  np_tree_s_np_clear_tree(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1insert_1str(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jstring jarg3, jlong jarg4) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  char *arg3 = (char *) 0 ;
  np_val_t arg4 ;
  $self *argp2 ;
  np_val_t *argp4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return ;
  }
  arg2 = *argp2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  argp4 = *(np_val_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_val_t");
    return ;
  }
  arg4 = *argp4; 
  np_tree_s_tree_insert_str(arg1,arg2,(char const *)arg3,arg4);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1insert_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  int16_t arg3 ;
  np_val_t arg4 ;
  $self *argp2 ;
  int16_t *argp3 ;
  np_val_t *argp4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return ;
  }
  arg2 = *argp2; 
  argp3 = *(int16_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int16_t");
    return ;
  }
  arg3 = *argp3; 
  argp4 = *(np_val_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_val_t");
    return ;
  }
  arg4 = *argp4; 
  np_tree_s_tree_insert_int(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1insert_1ulong(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  uint32_t arg3 ;
  np_val_t arg4 ;
  $self *argp2 ;
  uint32_t *argp3 ;
  np_val_t *argp4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return ;
  }
  arg2 = *argp2; 
  argp3 = *(uint32_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t");
    return ;
  }
  arg3 = *argp3; 
  argp4 = *(np_val_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_val_t");
    return ;
  }
  arg4 = *argp4; 
  np_tree_s_tree_insert_ulong(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1insert_1dbl(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jdouble jarg3, jlong jarg4) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  double arg3 ;
  np_val_t arg4 ;
  $self *argp2 ;
  np_val_t *argp4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return ;
  }
  arg2 = *argp2; 
  arg3 = (double)jarg3; 
  argp4 = *(np_val_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_val_t");
    return ;
  }
  arg4 = *argp4; 
  np_tree_s_tree_insert_dbl(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1replace_1str(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jstring jarg3, jlong jarg4) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  char *arg3 = (char *) 0 ;
  np_val_t arg4 ;
  $self *argp2 ;
  np_val_t *argp4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return ;
  }
  arg2 = *argp2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  argp4 = *(np_val_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_val_t");
    return ;
  }
  arg4 = *argp4; 
  np_tree_s_tree_replace_str(arg1,arg2,(char const *)arg3,arg4);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1replace_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  int16_t arg3 ;
  np_val_t arg4 ;
  $self *argp2 ;
  int16_t *argp3 ;
  np_val_t *argp4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return ;
  }
  arg2 = *argp2; 
  argp3 = *(int16_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int16_t");
    return ;
  }
  arg3 = *argp3; 
  argp4 = *(np_val_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_val_t");
    return ;
  }
  arg4 = *argp4; 
  np_tree_s_tree_replace_int(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1replace_1ulong(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  uint32_t arg3 ;
  np_val_t arg4 ;
  $self *argp2 ;
  uint32_t *argp3 ;
  np_val_t *argp4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return ;
  }
  arg2 = *argp2; 
  argp3 = *(uint32_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t");
    return ;
  }
  arg3 = *argp3; 
  argp4 = *(np_val_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_val_t");
    return ;
  }
  arg4 = *argp4; 
  np_tree_s_tree_replace_ulong(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1replace_1dbl(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jdouble jarg3, jlong jarg4) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  double arg3 ;
  np_val_t arg4 ;
  $self *argp2 ;
  np_val_t *argp4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return ;
  }
  arg2 = *argp2; 
  arg3 = (double)jarg3; 
  argp4 = *(np_val_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_val_t");
    return ;
  }
  arg4 = *argp4; 
  np_tree_s_tree_replace_dbl(arg1,arg2,arg3,arg4);
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1find_1str(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jstring jarg3) {
  jlong jresult = 0 ;
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  char *arg3 = (char *) 0 ;
  $self *argp2 ;
  np_tree_elem_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (np_tree_elem_t *)np_tree_s_tree_find_str(arg1,arg2,(char const *)arg3);
  *(np_tree_elem_t **)&jresult = result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1find_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  int16_t arg3 ;
  $self *argp2 ;
  int16_t *argp3 ;
  np_tree_elem_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(int16_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int16_t");
    return 0;
  }
  arg3 = *argp3; 
  result = (np_tree_elem_t *)np_tree_s_tree_find_int(arg1,arg2,arg3);
  *(np_tree_elem_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1find_1ulong(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  uint32_t arg3 ;
  $self *argp2 ;
  uint32_t *argp3 ;
  np_tree_elem_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(uint32_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t");
    return 0;
  }
  arg3 = *argp3; 
  result = (np_tree_elem_t *)np_tree_s_tree_find_ulong(arg1,arg2,arg3);
  *(np_tree_elem_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1find_1dbl(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jdouble jarg3) {
  jlong jresult = 0 ;
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  double arg3 ;
  $self *argp2 ;
  np_tree_elem_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (double)jarg3; 
  result = (np_tree_elem_t *)np_tree_s_tree_find_dbl(arg1,arg2,arg3);
  *(np_tree_elem_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1find_1gte_1str(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jstring jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  char *arg3 = (char *) 0 ;
  uint8_t *arg4 = (uint8_t *) 0 ;
  $self *argp2 ;
  np_tree_elem_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(uint8_t **)&jarg4; 
  result = (np_tree_elem_t *)np_tree_s_tree_find_gte_str(arg1,arg2,(char const *)arg3,arg4);
  *(np_tree_elem_t **)&jresult = result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1find_1gte_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  int16_t arg3 ;
  uint8_t *arg4 = (uint8_t *) 0 ;
  $self *argp2 ;
  int16_t *argp3 ;
  np_tree_elem_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(int16_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int16_t");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(uint8_t **)&jarg4; 
  result = (np_tree_elem_t *)np_tree_s_tree_find_gte_int(arg1,arg2,arg3,arg4);
  *(np_tree_elem_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1find_1gte_1ulong(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  uint32_t arg3 ;
  uint8_t *arg4 = (uint8_t *) 0 ;
  $self *argp2 ;
  uint32_t *argp3 ;
  np_tree_elem_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(uint32_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(uint8_t **)&jarg4; 
  result = (np_tree_elem_t *)np_tree_s_tree_find_gte_ulong(arg1,arg2,arg3,arg4);
  *(np_tree_elem_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1find_1gte_1dbl(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jdouble jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  double arg3 ;
  uint8_t *arg4 = (uint8_t *) 0 ;
  $self *argp2 ;
  np_tree_elem_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (double)jarg3; 
  arg4 = *(uint8_t **)&jarg4; 
  result = (np_tree_elem_t *)np_tree_s_tree_find_gte_dbl(arg1,arg2,arg3,arg4);
  *(np_tree_elem_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1del_1str(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jstring jarg3) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  char *arg3 = (char *) 0 ;
  $self *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return ;
  }
  arg2 = *argp2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  np_tree_s_tree_del_str(arg1,arg2,(char const *)arg3);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1del_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  int16_t arg3 ;
  $self *argp2 ;
  int16_t const *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return ;
  }
  arg2 = *argp2; 
  argp3 = *(int16_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int16_t const");
    return ;
  }
  arg3 = *argp3; 
  np_tree_s_tree_del_int(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1del_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jdouble jarg3) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  double arg3 ;
  $self *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return ;
  }
  arg2 = *argp2; 
  arg3 = (double)jarg3; 
  np_tree_s_tree_del_double(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1s_1tree_1del_1ulong(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  struct np_tree_s *arg1 = (struct np_tree_s *) 0 ;
  $self arg2 ;
  uint32_t arg3 ;
  $self *argp2 ;
  uint32_t const *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_s **)&jarg1; 
  argp2 = *($self **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null $self");
    return ;
  }
  arg2 = *argp2; 
  argp3 = *(uint32_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t const");
    return ;
  }
  arg3 = *argp3; 
  np_tree_s_tree_del_ulong(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1elem_1s_1key_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct np_tree_elem_s *arg1 = (struct np_tree_elem_s *) 0 ;
  np_val_t arg2 ;
  np_val_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_elem_s **)&jarg1; 
  argp2 = *(np_val_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_val_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->key = arg2;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1tree_1elem_1s_1key_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct np_tree_elem_s *arg1 = (struct np_tree_elem_s *) 0 ;
  np_val_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_elem_s **)&jarg1; 
  result =  ((arg1)->key);
  {
    np_val_t * resultptr = (np_val_t *) malloc(sizeof(np_val_t));
    memmove(resultptr, &result, sizeof(np_val_t));
    *(np_val_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1tree_1elem_1s_1val_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct np_tree_elem_s *arg1 = (struct np_tree_elem_s *) 0 ;
  np_val_t arg2 ;
  np_val_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_elem_s **)&jarg1; 
  argp2 = *(np_val_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_val_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->val = arg2;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1tree_1elem_1s_1val_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct np_tree_elem_s *arg1 = (struct np_tree_elem_s *) 0 ;
  np_val_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_tree_elem_s **)&jarg1; 
  result =  ((arg1)->val);
  {
    np_val_t * resultptr = (np_val_t *) malloc(sizeof(np_val_t));
    memmove(resultptr, &result, sizeof(np_val_t));
    *(np_val_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_new_1np_1tree_1elem_1s(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct np_tree_elem_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct np_tree_elem_s *)calloc(1, sizeof(struct np_tree_elem_s));
  *(struct np_tree_elem_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_delete_1np_1tree_1elem_1s(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct np_tree_elem_s *arg1 = (struct np_tree_elem_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct np_tree_elem_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jstring JNICALL Java_neuropilJNI_np_1create_1uuid(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  jstring jresult = 0 ;
  char *arg1 = (char *) 0 ;
  uint16_t arg2 ;
  uint16_t const *argp2 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  argp2 = *(uint16_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint16_t const");
    return 0;
  }
  arg2 = *argp2; 
  result = (char *)np_create_uuid((char const *)arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_DEFAULT_1MODE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mode_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mode_enum)DEFAULT_MODE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_INBOUND_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mode_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mode_enum)INBOUND;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_OUTBOUND_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mode_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mode_enum)OUTBOUND;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_ROUTE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mode_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mode_enum)ROUTE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_TRANSFORM_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mode_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mode_enum)TRANSFORM;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_DEFAULT_1TYPE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)DEFAULT_TYPE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_RECEIVER_1MASK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)RECEIVER_MASK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_SENDER_1MASK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)SENDER_MASK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_FILTER_1MASK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)FILTER_MASK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_SINGLE_1RECEIVER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)SINGLE_RECEIVER;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_GROUP_1RECEIVER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)GROUP_RECEIVER;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_ANY_1RECEIVER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)ANY_RECEIVER;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_SINGLE_1SENDER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)SINGLE_SENDER;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_GROUP_1SENDER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)GROUP_SENDER;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_ANY_1SENDER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)ANY_SENDER;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_FILTER_1MSG_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)FILTER_MSG;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_HAS_1REPLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)HAS_REPLY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_STICKY_1REPLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)STICKY_REPLY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_ONE_1WAY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)ONE_WAY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_ONE_1WAY_1WITH_1REPLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)ONE_WAY_WITH_REPLY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_ONE_1TO_1GROUP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)ONE_TO_GROUP;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_O2G_1WITH_1REPLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)O2G_WITH_REPLY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_ONE_1TO_1ANY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)ONE_TO_ANY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_O2A_1WITH_1REPLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)O2A_WITH_REPLY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_GROUP_1TO_1GROUP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)GROUP_TO_GROUP;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_G2G_1WITH_1REPLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)G2G_WITH_REPLY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_G2G_1STICKY_1REPLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)G2G_STICKY_REPLY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_ANY_1TO_1ANY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)ANY_TO_ANY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_A2A_1WITH_1REPLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)A2A_WITH_REPLY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_A2A_1STICKY_1REPLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)A2A_STICKY_REPLY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_GROUP_1TO_1ANY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)GROUP_TO_ANY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_G2A_1WITH_1REPLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)G2A_WITH_REPLY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_G2A_1STICKY_1REPLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)G2A_STICKY_REPLY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_ANY_1TO_1GROUP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)ANY_TO_GROUP;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_A2G_1WITH_1REPLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)A2G_WITH_REPLY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_A2G_1STICKY_1REPLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)A2G_STICKY_REPLY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_REQ_1REP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)REQ_REP;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_PIPELINE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)PIPELINE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_AGGREGATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)AGGREGATE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_MULTICAST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)MULTICAST;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_BROADCAST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)BROADCAST;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_INTERVIEW_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)INTERVIEW;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_BUS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)BUS;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_SURVEY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)SURVEY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_PUBSUB_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_mep_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_mep_enum)PUBSUB;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_FIFO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msgcache_policy_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msgcache_policy_enum)FIFO;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_FILO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msgcache_policy_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msgcache_policy_enum)FILO;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_OVERFLOW_1REJECT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msgcache_policy_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msgcache_policy_enum)OVERFLOW_REJECT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_OVERFLOW_1PURGE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msgcache_policy_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msgcache_policy_enum)OVERFLOW_PURGE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_ACK_1NONE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_ack_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_ack_enum)ACK_NONE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_ACK_1EACHHOP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_ack_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_ack_enum)ACK_EACHHOP;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_ACK_1DESTINATION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_ack_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_ack_enum)ACK_DESTINATION;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_ACK_1CLIENT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_msg_ack_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_msg_ack_enum)ACK_CLIENT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1partner_1key_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  np_dhkey_t arg2 ;
  np_dhkey_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  argp2 = *(np_dhkey_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_dhkey_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->partner_key = arg2;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1msgproperty_1s_1partner_1key_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  np_dhkey_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result =  ((arg1)->partner_key);
  {
    np_dhkey_t * resultptr = (np_dhkey_t *) malloc(sizeof(np_dhkey_t));
    memmove(resultptr, &result, sizeof(np_dhkey_t));
    *(np_dhkey_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1msg_1subject_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->msg_subject);
    if (arg2) {
      arg1->msg_subject = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->msg_subject, (const char *)arg2);
    } else {
      arg1->msg_subject = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_neuropilJNI_np_1msgproperty_1s_1msg_1subject_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result = (char *) ((arg1)->msg_subject);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1rep_1subject_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->rep_subject);
    if (arg2) {
      arg1->rep_subject = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->rep_subject, (const char *)arg2);
    } else {
      arg1->rep_subject = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_neuropilJNI_np_1msgproperty_1s_1rep_1subject_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result = (char *) ((arg1)->rep_subject);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1msg_1audience_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->msg_audience);
    if (arg2) {
      arg1->msg_audience = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->msg_audience, (const char *)arg2);
    } else {
      arg1->msg_audience = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_neuropilJNI_np_1msgproperty_1s_1msg_1audience_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result = (char *) ((arg1)->msg_audience);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1mode_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  np_msg_mode_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  arg2 = (np_msg_mode_type)jarg2; 
  if (arg1) (arg1)->mode_type = arg2;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_np_1msgproperty_1s_1mode_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  np_msg_mode_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result = (np_msg_mode_type) ((arg1)->mode_type);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1mep_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  np_msg_mep_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  arg2 = (np_msg_mep_type)jarg2; 
  if (arg1) (arg1)->mep_type = arg2;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_np_1msgproperty_1s_1mep_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  np_msg_mep_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result = (np_msg_mep_type) ((arg1)->mep_type);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1ack_1mode_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  np_msg_ack_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  arg2 = (np_msg_ack_type)jarg2; 
  if (arg1) (arg1)->ack_mode = arg2;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_np_1msgproperty_1s_1ack_1mode_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  np_msg_ack_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result = (np_msg_ack_type) ((arg1)->ack_mode);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1ttl_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->ttl = arg2;
}


SWIGEXPORT jdouble JNICALL Java_neuropilJNI_np_1msgproperty_1s_1ttl_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result = (double) ((arg1)->ttl);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1priority_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  uint8_t arg2 ;
  uint8_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  argp2 = *(uint8_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint8_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->priority = arg2;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1msgproperty_1s_1priority_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result =  ((arg1)->priority);
  {
    uint8_t * resultptr = (uint8_t *) malloc(sizeof(uint8_t));
    memmove(resultptr, &result, sizeof(uint8_t));
    *(uint8_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1retry_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  uint8_t arg2 ;
  uint8_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  argp2 = *(uint8_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint8_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->retry = arg2;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1msgproperty_1s_1retry_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result =  ((arg1)->retry);
  {
    uint8_t * resultptr = (uint8_t *) malloc(sizeof(uint8_t));
    memmove(resultptr, &result, sizeof(uint8_t));
    *(uint8_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1msg_1threshold_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  uint16_t arg2 ;
  uint16_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  argp2 = *(uint16_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint16_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->msg_threshold = arg2;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1msgproperty_1s_1msg_1threshold_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  uint16_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result =  ((arg1)->msg_threshold);
  {
    uint16_t * resultptr = (uint16_t *) malloc(sizeof(uint16_t));
    memmove(resultptr, &result, sizeof(uint16_t));
    *(uint16_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1max_1threshold_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  uint16_t arg2 ;
  uint16_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  argp2 = *(uint16_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint16_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->max_threshold = arg2;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1msgproperty_1s_1max_1threshold_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  uint16_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result =  ((arg1)->max_threshold);
  {
    uint16_t * resultptr = (uint16_t *) malloc(sizeof(uint16_t));
    memmove(resultptr, &result, sizeof(uint16_t));
    *(uint16_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1last_1update_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->last_update = arg2;
}


SWIGEXPORT jdouble JNICALL Java_neuropilJNI_np_1msgproperty_1s_1last_1update_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result = (double) ((arg1)->last_update);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1cache_1policy_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  np_msgcache_policy_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  arg2 = (np_msgcache_policy_type)jarg2; 
  if (arg1) (arg1)->cache_policy = arg2;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_np_1msgproperty_1s_1cache_1policy_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  np_msgcache_policy_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result = (np_msgcache_policy_type) ((arg1)->cache_policy);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1s_1user_1clb_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  np_usercallback_t arg2 = (np_usercallback_t) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  arg2 = *(np_usercallback_t *)&jarg2; 
  if (arg1) (arg1)->user_clb = arg2;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1msgproperty_1s_1user_1clb_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  np_usercallback_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  result = (np_usercallback_t) ((arg1)->user_clb);
  *(np_usercallback_t *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_new_1np_1msgproperty_1s(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct np_msgproperty_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct np_msgproperty_s *)calloc(1, sizeof(struct np_msgproperty_s));
  *(struct np_msgproperty_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_delete_1np_1msgproperty_1s(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct np_msgproperty_s *arg1 = (struct np_msgproperty_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct np_msgproperty_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1msgproperty_1register(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  np_msgproperty_t *arg1 = (np_msgproperty_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(np_msgproperty_t **)&jarg1; 
  np_msgproperty_register(arg1);
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1msgproperty_1get(JNIEnv *jenv, jclass jcls, jint jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  np_msg_mode_type arg1 ;
  char *arg2 = (char *) 0 ;
  np_msgproperty_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (np_msg_mode_type)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (np_msgproperty_t *)np_msgproperty_get(arg1,(char const *)arg2);
  *(np_msgproperty_t **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1mem_1newobj(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  np_obj_enum arg1 ;
  np_obj_t **arg2 = (np_obj_t **) 0 ;
  np_obj_enum *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(np_obj_enum **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_obj_enum");
    return ;
  }
  arg1 = *argp1; 
  arg2 = *(np_obj_t ***)&jarg2; 
  np_mem_newobj(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1mem_1freeobj(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  np_obj_enum arg1 ;
  np_obj_t **arg2 = (np_obj_t **) 0 ;
  np_obj_enum *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(np_obj_enum **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_obj_enum");
    return ;
  }
  arg1 = *argp1; 
  arg2 = *(np_obj_t ***)&jarg2; 
  np_mem_freeobj(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1mem_1refobj(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  np_obj_t *arg1 = (np_obj_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(np_obj_t **)&jarg1; 
  np_mem_refobj(arg1);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1mem_1unrefobj(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  np_obj_t *arg1 = (np_obj_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(np_obj_t **)&jarg1; 
  np_mem_unrefobj(arg1);
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1NONE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_NONE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1NOMOD_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_NOMOD;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1ERROR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_ERROR;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1WARN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_WARN;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1INFO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_INFO;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1DEBUG_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_DEBUG;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1TRACE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_TRACE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1KEY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_KEY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1NETWORK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_NETWORK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1ROUTING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_ROUTING;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1MESSAGE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_MESSAGE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1SECURE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_SECURE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1HTTP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_HTTP;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1AAATOKEN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_AAATOKEN;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1GLOBAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_GLOBAL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1MODUL_1MASK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_MODUL_MASK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neuropilJNI_LOG_1NOMOD_1MASK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum np_log_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum np_log_e)LOG_NOMOD_MASK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1log_1init(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  char *arg1 = (char *) 0 ;
  uint16_t arg2 ;
  uint16_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  argp2 = *(uint16_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint16_t");
    return ;
  }
  arg2 = *argp2; 
  np_log_init((char const *)arg1,arg2);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1log_1setlevel(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  uint16_t arg1 ;
  uint16_t *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(uint16_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint16_t");
    return ;
  }
  arg1 = *argp1; 
  np_log_setlevel(arg1);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1log_1destroy(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  np_log_destroy();
}


SWIGEXPORT void JNICALL Java_neuropilJNI__1np_1add_1http_1callback(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  char *arg1 = (char *) 0 ;
  htp_method arg2 ;
  void *arg3 = (void *) 0 ;
  _np_http_callback_func_t arg4 ;
  htp_method *argp2 ;
  _np_http_callback_func_t *argp4 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  argp2 = *(htp_method **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null htp_method");
    return ;
  }
  arg2 = *argp2; 
  arg3 = *(void **)&jarg3; 
  argp4 = *(_np_http_callback_func_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null _np_http_callback_func_t");
    return ;
  }
  arg4 = *argp4; 
  _np_add_http_callback((char const *)arg1,arg2,arg3,arg4);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_neuropilJNI__1np_1rem_1http_1callback(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  char *arg1 = (char *) 0 ;
  htp_method arg2 ;
  htp_method *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  argp2 = *(htp_method **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null htp_method");
    return ;
  }
  arg2 = *argp2; 
  _np_rem_http_callback((char const *)arg1,arg2);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1init(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  np_bool arg3 ;
  np_bool *argp3 ;
  np_state_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  argp3 = *(np_bool **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null np_bool");
    return 0;
  }
  arg3 = *argp3; 
  result = (np_state_t *)np_init(arg1,arg2,arg3);
  *(np_state_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1destroy(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  np_destroy();
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1enable_1realm_1master(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  np_enable_realm_master();
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1enable_1realm_1slave(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  np_enable_realm_slave();
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1set_1realm_1name(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  np_set_realm_name((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1set_1identity(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  np_aaatoken_t *arg1 = (np_aaatoken_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(np_aaatoken_t **)&jarg1; 
  np_set_identity(arg1);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1send_1join(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  np_send_join((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1waitforjoin(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  np_waitforjoin();
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1setauthorizing_1cb(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  np_aaa_func_t arg1 = (np_aaa_func_t) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(np_aaa_func_t *)&jarg1; 
  np_setauthorizing_cb(arg1);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1setauthenticate_1cb(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  np_aaa_func_t arg1 = (np_aaa_func_t) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(np_aaa_func_t *)&jarg1; 
  np_setauthenticate_cb(arg1);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1setaccounting_1cb(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  np_aaa_func_t arg1 = (np_aaa_func_t) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(np_aaa_func_t *)&jarg1; 
  np_setaccounting_cb(arg1);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1set_1listener(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  np_usercallback_t arg1 = (np_usercallback_t) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(np_usercallback_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  np_set_listener(arg1,arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1send_1text(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jlong jarg3) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  uint32_t arg3 ;
  uint32_t *argp3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  argp3 = *(uint32_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t");
    return ;
  }
  arg3 = *argp3; 
  np_send_text(arg1,arg2,arg3);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1send_1msg(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jlong jarg3) {
  char *arg1 = (char *) 0 ;
  np_tree_t *arg2 = (np_tree_t *) 0 ;
  np_tree_t *arg3 = (np_tree_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  arg2 = *(np_tree_t **)&jarg2; 
  arg3 = *(np_tree_t **)&jarg3; 
  np_send_msg(arg1,arg2,arg3);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1receive_1text(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char **arg2 = (char **) 0 ;
  uint32_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(char ***)&jarg2; 
  result = np_receive_text(arg1,arg2);
  {
    uint32_t * resultptr = (uint32_t *) malloc(sizeof(uint32_t));
    memmove(resultptr, &result, sizeof(uint32_t));
    *(uint32_t **)&jresult = resultptr;
  }
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_neuropilJNI_np_1receive_1msg(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  np_tree_t *arg2 = (np_tree_t *) 0 ;
  np_tree_t *arg3 = (np_tree_t *) 0 ;
  uint32_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(np_tree_t **)&jarg2; 
  arg3 = *(np_tree_t **)&jarg3; 
  result = np_receive_msg(arg1,arg2,arg3);
  {
    uint32_t * resultptr = (uint32_t *) malloc(sizeof(uint32_t));
    memmove(resultptr, &result, sizeof(uint32_t));
    *(uint32_t **)&jresult = resultptr;
  }
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_neuropilJNI_np_1start_1job_1queue(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  uint8_t arg1 ;
  uint8_t *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(uint8_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint8_t");
    return ;
  }
  arg1 = *argp1; 
  np_start_job_queue(arg1);
}


#ifdef __cplusplus
}
#endif

